/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.kolaborasa.view;

import com.mycompany.kolaborasa.controller.IdeController;

/**
 *
 * @author Sadid
 */
public class ListIdeView extends javax.swing.JFrame {

    private String userEmailAktif;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ListIdeView.class.getName());
    private IdeController controller = new IdeController();

    public javax.swing.JTable getTabelIde() {
        return tabelIde;
    }

    /**
     * Creates new form ListIdeView
     */
    public ListIdeView() {
        initComponents();

        System.out.println("Memulai memuat data ke tabel...");
        loadData();
    }

    public void loadData() {
        controller.tampilkanDataKeTabel(this);
    }

    public ListIdeView(String email) {
        initComponents();
        this.userEmailAktif = email;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBeranda = new javax.swing.JButton();
        btnListIde = new javax.swing.JButton();
        btnProfil = new javax.swing.JButton();
        btnTambahIde = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelIde = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblDetailGambar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDetailTeks = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 0, 255));

        btnBeranda.setText("Beranda");
        btnBeranda.addActionListener(this::btnBerandaActionPerformed);

        btnListIde.setText("List Ide");

        btnProfil.setText("Profil");
        btnProfil.addActionListener(this::btnProfilActionPerformed);

        btnTambahIde.setText("Tambah Ide");
        btnTambahIde.addActionListener(this::btnTambahIdeActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnListIde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTambahIde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBeranda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnBeranda)
                .addGap(18, 18, 18)
                .addComponent(btnListIde)
                .addGap(16, 16, 16)
                .addComponent(btnTambahIde)
                .addGap(18, 18, 18)
                .addComponent(btnProfil)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabelIde.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Judul", "Deskripsi", "Path Gambar"
            }
        ));
        tabelIde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelIdeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelIde);

        jLabel1.setText("List Ide");

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        lblDetailGambar.setText("Preview Gambar");

        txtDetailTeks.setColumns(20);
        txtDetailTeks.setRows(5);
        jScrollPane2.setViewportView(txtDetailTeks);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDetailGambar)
                .addGap(133, 133, 133))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(lblDetailGambar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tabelIdeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelIdeMouseClicked
        // TODO add your handling code here:
        int row = tabelIde.getSelectedRow();

        // Pastikan ada baris yang benar-benar diklik
        if (row != -1) {
            try {
                // Ambil data secara aman dengan mengecek apakah nilainya null atau tidak
                Object valJudul = tabelIde.getValueAt(row, 1);
                Object valDeskripsi = tabelIde.getValueAt(row, 2);
                Object valPath = tabelIde.getValueAt(row, 3);

                String judul = (valJudul != null) ? valJudul.toString() : "Tanpa Judul";
                String deskripsi = (valDeskripsi != null) ? valDeskripsi.toString() : "";
                String path = (valPath != null) ? valPath.toString() : "";

                // Tampilkan ke komponen detail teks sebelah kanan
                txtDetailTeks.setText("Judul: " + judul + "\n\nDeskripsi:\n" + deskripsi);

                // LOGIKA RESIZE GAMBAR PROPORSIONAL LANGSUNG DI SINI
                if (path != null && !path.isEmpty()) {
                    java.io.File fileGambar = new java.io.File(path);
                    if (fileGambar.exists()) {
                        javax.swing.ImageIcon icon = new javax.swing.ImageIcon(path);

                        // 1. Ambil ukuran asli gambar dari file
                        int gambarWidth = icon.getIconWidth();
                        int gambarHeight = icon.getIconHeight();

                        // 2. Tentukan batas maksimal ukuran kotak gambar di GUI Anda
                        int max_w = 300;
                        int max_h = 200;

                        // 3. Hitung rasio baru (Skala Proporsional)
                        int new_w = gambarWidth;
                        int new_h = gambarHeight;

                        if (gambarWidth > max_w) {
                            new_w = max_w;
                            new_h = (new_w * gambarHeight) / gambarWidth;
                        }

                        if (new_h > max_h) {
                            new_h = max_h;
                            new_w = (new_h * gambarWidth) / gambarHeight;
                        }

                        // 4. Ubah ukuran gambar menggunakan ukuran proporsional
                        java.awt.Image img = icon.getImage().getScaledInstance(new_w, new_h, java.awt.Image.SCALE_SMOOTH);

                        // 5. Tampilkan ke JLabel
                        lblDetailGambar.setIcon(new javax.swing.ImageIcon(img));
                        lblDetailGambar.setText("");
                    } else {
                        lblDetailGambar.setIcon(null);
                        lblDetailGambar.setText("File gambar tidak ditemukan");
                    }
                } else {
                    lblDetailGambar.setIcon(null);
                    lblDetailGambar.setText("Tidak ada gambar");
                }

            } catch (Exception e) {
                System.out.println("Error saat mengambil data tabel: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_tabelIdeMouseClicked

    private void btnProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfilActionPerformed
        // TODO add your handling code here:
        ProfilView halamanProfil = new ProfilView();
        halamanProfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnProfilActionPerformed

    private void btnTambahIdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahIdeActionPerformed
        // TODO add your handling code here:
        InputIdeView halamanInput = new InputIdeView();
        halamanInput.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnTambahIdeActionPerformed

    private void btnBerandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBerandaActionPerformed
        // TODO add your handling code here:
        HomeView halamanHome = new HomeView();
        halamanHome.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBerandaActionPerformed

    // Fungsi ini menghitung ukuran gambar agar fit di JLabel dengan rasio yang benar
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ListIdeView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBeranda;
    private javax.swing.JButton btnListIde;
    private javax.swing.JButton btnProfil;
    private javax.swing.JButton btnTambahIde;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDetailGambar;
    private javax.swing.JTable tabelIde;
    private javax.swing.JTextArea txtDetailTeks;
    // End of variables declaration//GEN-END:variables
}
